{
printParameters         : true,
savePath                : "/home/unnar/catkin_ws/src/rosOgre/run_from/",
#cloudPath              : "/home/unnar/catkin_ws/src/Metarooms/room_2/intermediate_cloud0043.pcd",
cloudPath               : "/home/unnar/catkin_ws/src/Metarooms/room_2/intermediate_cloud0007.pcd",
#cloudPath              : "/home/unnar/catkin_ws/src/Metarooms/room_2/intermediate_cloud0020.pcd",
#cloudPath              : "/home/unnar/catkin_ws/src/Metarooms/room_3/complete_cloud.pcd",
configPath              : "/home/unnar/catkin_ws/src/rosOgre/dist/bin/",
VoxelLeafSize           : 0.02,
SVVoxelResolution       : 0.05,
SVSeedResolution        : 0.1,
SVColorImportance       : 0.1,
SVSpatialImportance     : 5.0,
RANSACDistanceThreshold : 0.08,
RANSACMinInliers        : 200,
GP3SearchRad            : 3.0,
GP3Mu                   : 4.5,
GP3MaxNearestNeighbours : 50,
GP3Ksearch              : 8,
RWHullMaxDist           : 0.05,
ECMinClusterSize        : 20,
ECClusterTolerance      : 0.04,
simplifyHulls           : true,
hullAlpha               : 0.03,

# TOPICS
TOPIC_POINT_CLOUD       : "/camera/depth_registered/points",
}